/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ilib;

import com.mycompany.interfaces.DAOEmployees;
import org.apache.commons.lang3.StringUtils;
import com.mycompany.models.Employees;
/**
 *
 * @author MANUEL
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
 public Login() {
        initComponents();

        // Centrar ventana
        setLocationRelativeTo(null);

        // Título y diseño
        setTitle("Inicio de Sesión - iLib");
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(60, 63, 65)); // gris oscuro

        // Estilo de etiquetas
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        // Campos de texto
        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setForeground(new java.awt.Color(0, 0, 0));

        txtClave.setBackground(new java.awt.Color(255, 255, 255));
        txtClave.setForeground(new java.awt.Color(0, 0, 0));

        // Botón
        btnLogin.setBackground(new java.awt.Color(33, 150, 243)); // azul
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setFocusPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Clave");

        btnLogin.setText("Iniciar Sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtClave.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtClaveInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtClave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnLogin)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLogin)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (StringUtils.isBlank(txtUser.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre de usuario", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            txtUser.requestFocus();
            return;
        }else if (StringUtils.isBlank(txtClave.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese la clave", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            txtClave.requestFocus();
            return;
        }
        try{
            DAOEmployees dao = new DAOEmployeesImpl();
            if(dao.getEmployeeByUser(txtUser.getText()) == null){
                javax.swing.JOptionPane.showMessageDialog(this, "El usuario no se encuentra registrado. Si crees que se trata de un error consulta con la administración", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                txtUser.requestFocus();
            }else{
                if(dao.getEmployee(txtUser.getText(), txtClave.getText()) == null){
                    javax.swing.JOptionPane.showMessageDialog(this, "La contraseña es incorrecta. Si crees que se trata de un error consulta con la administración", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                    txtClave.requestFocus();
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Inicio de Sesion Exitoso", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new Dashboard(txtUser.getText()).setVisible(true);
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtClaveInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtClaveInputMethodTextChanged
        // TODO add your handling code here:
        if (StringUtils.isBlank(txtUser.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre de usuario", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            txtUser.requestFocus();
            return;
        }else if (StringUtils.isBlank(txtClave.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese la clave", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            txtClave.requestFocus();
            return;
        }
        try{
            DAOEmployees dao = new DAOEmployeesImpl();
            if(dao.getEmployeeByUser(txtUser.getText()) == null){
                javax.swing.JOptionPane.showMessageDialog(this, "El usuario no se encuentra registrado. Si crees que se trata de un error consulta con la administración", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                txtUser.requestFocus();
            }else{
                if(dao.getEmployee(txtUser.getText(), txtClave.getText()) == null){
                    javax.swing.JOptionPane.showMessageDialog(this, "La contraseña es incorrecta. Si crees que se trata de un error consulta con la administración", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                    txtClave.requestFocus();
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Inicio de Sesion Exitoso", "ERROR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    new Dashboard(txtUser.getText()).setVisible(true);
                }
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtClaveInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
