package com.mycompany.views;

import java.awt.Color;
import com.mycompany.ilib.DAOBooksImpl;
import com.mycompany.ilib.Dashboard;
import com.mycompany.interfaces.DAOBooks;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import org.apache.commons.lang3.StringUtils;

public class UpBooks extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Books bookEdition;

    public UpBooks() {
        initComponents();
        InitStyles();
        
    }
    
    public UpBooks(com.mycompany.models.Books book) {
        initComponents();
        isEdition = true;
        bookEdition = book;
        InitStyles();
    }

    private void InitStyles(){
        title.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        title.setForeground(Color.black);
        LibroIdTxt.putClientProperty("JTextField.placeholderText", "La ID del libro se colocará automáticamente");
        LibroIdTxt.enable(false);
        titleTxt.putClientProperty("JTextField.placeholderText", "Ingrese el título del libro");
        dateTxt.putClientProperty("JTextField.placeholderText", "Ingrese la de publicación del libro.");
        authorTxt.putClientProperty("JTextField.placeholderText", "Ingrese el autor del libro.");
        catTxt.putClientProperty("JTextField.placeholderText", "Ingrese la categoría del libro.");
        edTxt.putClientProperty("JTextField.placeholderText", "Ingrese la editorial del libro.");
        langTxt.putClientProperty("JTextField.placeholderText", "Ingrese el idioma del libro.");
        pagsTxt.putClientProperty("JTextField.placeholderText", "Ingrese las páginas totales del libro.");
        descTxt.putClientProperty("JTextField.placeholderText", "Ingrese la descripción del libro.");
        stockTxt.putClientProperty("JTextField.placeholderText", "Ingrese el stock total del libro.");
        dispTxt.putClientProperty("JTextField.placeholderText", "Ingrese el númeor de libros disponibles.");
        ejemTxt.putClientProperty("JTextField.placeholderText", "Ingrese el número de ejemplares del libro.");
        if (isEdition) {
            title.setText("Editar Libro");
            button.setText("Guardar");
            lblCover.setVisible(false);
            imageChooser.setVisible(false);

            if (bookEdition != null) {
                LibroIdTxt.setText(String.valueOf(bookEdition.getId()));
                titleTxt.setText(bookEdition.getTitle());
                dateTxt.setText(bookEdition.getDate());
                authorTxt.setText(bookEdition.getAuthor());
                catTxt.setText(bookEdition.getCategory());
                edTxt.setText(bookEdition.getEdit());
                langTxt.setText(bookEdition.getLang());
                pagsTxt.setText(bookEdition.getPages());
                descTxt.setText(bookEdition.getDescription());
                stockTxt.setText(bookEdition.getStock() + "");
                dispTxt.setText(bookEdition.getAvailable() + "");
                ejemTxt.setText(bookEdition.getEjemplares());
            }
        }
    }
    //Metodo para mostrar panel
//    public static void ShowJPanel(JPanel p){
//        p.setSize(750,430);
//        p.setLocation(0,0);
//        
//        content.removeAll();
//        content.add(p, BorderLayout.CENTER);
//        content.revalidate();
//        content.repaint();   
//    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        button = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        edLbl = new javax.swing.JLabel();
        edTxt = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        dispTxt = new javax.swing.JTextField();
        dispLbl = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        authorLbl = new javax.swing.JLabel();
        authorTxt = new javax.swing.JTextField();
        catLbl = new javax.swing.JLabel();
        catTxt = new javax.swing.JTextField();
        LibroIdLbl = new javax.swing.JLabel();
        langLbl = new javax.swing.JLabel();
        pagsLbl = new javax.swing.JLabel();
        ejemLbl = new javax.swing.JLabel();
        LibroIdTxt = new javax.swing.JTextField();
        langTxt = new javax.swing.JTextField();
        pagsTxt = new javax.swing.JTextField();
        ejemTxt = new javax.swing.JTextField();
        stockLbl = new javax.swing.JLabel();
        stockTxt = new javax.swing.JTextField();
        descLbl = new javax.swing.JLabel();
        descTxt = new javax.swing.JTextField();
        lblCover = new javax.swing.JLabel();
        imageChooser = new javax.swing.JFileChooser();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setBackground(new java.awt.Color(247, 248, 249));
        background.setPreferredSize(new java.awt.Dimension(750, 430));

        jSeparator1.setBackground(new java.awt.Color(153, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 107));

        button.setBackground(new java.awt.Color(223, 38, 114));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Subir");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Subir nuevo Libro");

        edLbl.setText("Edicion");

        edTxt.setBackground(new java.awt.Color(241, 243, 244));
        edTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        edTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edTxtActionPerformed(evt);
            }
        });

        dateLbl.setText("Fecha de Publicacion");

        dispTxt.setBackground(new java.awt.Color(241, 243, 244));
        dispTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        dispTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispTxtActionPerformed(evt);
            }
        });

        dispLbl.setText("Disponibles");

        titleTxt.setBackground(new java.awt.Color(241, 243, 244));
        titleTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });

        dateTxt.setBackground(new java.awt.Color(241, 243, 244));
        dateTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });

        titleLbl.setText("Titulo");

        authorLbl.setText("Autor");

        authorTxt.setBackground(new java.awt.Color(241, 243, 244));
        authorTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        authorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorTxtActionPerformed(evt);
            }
        });

        catLbl.setText("Categoria");

        catTxt.setBackground(new java.awt.Color(241, 243, 244));
        catTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        catTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catTxtActionPerformed(evt);
            }
        });

        LibroIdLbl.setText("Libro ID");

        langLbl.setText("Idiomas");

        pagsLbl.setText("Paginas");

        ejemLbl.setText("Ejemplares");

        LibroIdTxt.setBackground(new java.awt.Color(241, 243, 244));
        LibroIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        LibroIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroIdTxtActionPerformed(evt);
            }
        });

        langTxt.setBackground(new java.awt.Color(241, 243, 244));
        langTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        langTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langTxtActionPerformed(evt);
            }
        });

        pagsTxt.setBackground(new java.awt.Color(241, 243, 244));
        pagsTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        pagsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagsTxtActionPerformed(evt);
            }
        });

        ejemTxt.setBackground(new java.awt.Color(241, 243, 244));
        ejemTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        ejemTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemTxtActionPerformed(evt);
            }
        });

        stockLbl.setText("Stock");

        stockTxt.setBackground(new java.awt.Color(241, 243, 244));
        stockTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        stockTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTxtActionPerformed(evt);
            }
        });

        descLbl.setText("Descripcion");

        descTxt.setBackground(new java.awt.Color(241, 243, 244));
        descTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 243, 244), 1, true));
        descTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTxtActionPerformed(evt);
            }
        });

        lblCover.setText("Portada");

        btnCancel.setBackground(new java.awt.Color(223, 38, 114));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LibroIdLbl)
                            .addComponent(LibroIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLbl)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLbl)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorLbl)
                            .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catLbl)
                            .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edLbl)
                            .addComponent(edTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(langLbl)
                                        .addGap(268, 268, 268)
                                        .addComponent(lblCover))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(pagsLbl)
                                            .addComponent(pagsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(descLbl)
                                            .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(stockLbl)
                                                .addGap(121, 121, 121)
                                                .addComponent(dispLbl))
                                            .addComponent(ejemLbl)
                                            .addComponent(ejemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(langTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(imageChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(title)
                .addGap(14, 14, 14)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(LibroIdLbl)
                        .addGap(14, 14, 14)
                        .addComponent(LibroIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(titleLbl)
                        .addGap(4, 4, 4)
                        .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dateLbl)
                        .addGap(4, 4, 4)
                        .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(authorLbl)
                        .addGap(4, 4, 4)
                        .addComponent(authorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(catLbl)
                        .addGap(4, 4, 4)
                        .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(edLbl)
                        .addGap(4, 4, 4)
                        .addComponent(edTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(langLbl)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                .addComponent(lblCover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(langTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(pagsLbl)
                                .addGap(4, 4, 4)
                                .addComponent(pagsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(descLbl)
                                .addGap(4, 4, 4)
                                .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stockLbl)
                                    .addComponent(dispLbl))
                                .addGap(4, 4, 4)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(ejemLbl)
                                .addGap(4, 4, 4)
                                .addComponent(ejemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imageChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        File image = imageChooser.getSelectedFile();
        File destDir = new File("src/main/resources/images");
        String mtitle = titleTxt.getText();
        String date = dateTxt.getText();
        String author = authorTxt.getText();
        String cat = catTxt.getText();
        String ed = edTxt.getText();
        String lang = langTxt.getText();
        String pags = pagsTxt.getText();
        String desc = descTxt.getText();
        String stock = stockTxt.getText();
        String disp = dispTxt.getText();
        String ejem = ejemTxt.getText();

        // Validaciones para los campos con Apache Commons
        if (StringUtils.isBlank(mtitle) || StringUtils.isBlank(date) || StringUtils.isBlank(author) || StringUtils.isBlank(cat) || StringUtils.isBlank(ed)
                || StringUtils.isBlank(lang) || StringUtils.isBlank(pags) || StringUtils.isBlank(desc) || StringUtils.isBlank(stock) || StringUtils.isBlank(disp) || StringUtils.isBlank(ejem)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        } else if (!StringUtils.isNumeric(stock) || !StringUtils.isNumeric(disp)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos Stock y Disponibles deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            titleTxt.requestFocus();
            return;
        }
        if(image == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una imagen para la portada. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            imageChooser.requestFocus();
            return;
        }
        if(!image.getName().endsWith("png") && !image.getName().endsWith("jpg") && !image.getName().endsWith("jpeg")){
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de imagen incorrecto(Formatos permitidos: PNG, JPG, JPEG) \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            imageChooser.requestFocus();
            return;
        }
        String newFileName = image.getName();
        File destFile = new File(destDir,newFileName);
        com.mycompany.models.Books book = isEdition ? bookEdition : new com.mycompany.models.Books();
        book.setTitle(mtitle);
        book.setDate(date);
        book.setAuthor(author);
        book.setCategory(cat);
        book.setEdit(ed);
        book.setLang(lang);
        book.setImage(newFileName);
        book.setPages(pags);
        book.setDescription(desc);
        book.setEjemplares(ejem);
        book.setStock(Integer.parseInt(stock));
        book.setAvailable(Integer.parseInt(disp));

        try {
            Files.copy(image.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            DAOBooks dao = new DAOBooksImpl();

            if (!isEdition) {
                dao.registrar(book);
            } else {
                dao.modificar(book);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                titleTxt.setText("");
                dateTxt.setText("");
                authorTxt.setText("");
                catTxt.setText("");
                edTxt.setText("");
                langTxt.setText("");
                pagsTxt.setText("");
                descTxt.setText("");
                stockTxt.setText("");
                dispTxt.setText("");
                ejemTxt.setText("");
            }
            
            Dashboard.ShowJPanel(new Books());
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void edTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edTxtActionPerformed

    private void dispTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dispTxtActionPerformed

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed

    private void authorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorTxtActionPerformed

    private void catTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catTxtActionPerformed

    private void LibroIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibroIdTxtActionPerformed

    private void langTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langTxtActionPerformed

    private void pagsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagsTxtActionPerformed

    private void ejemTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemTxtActionPerformed

    private void stockTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTxtActionPerformed

    private void descTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTxtActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        Dashboard.ShowJPanel(new Books());
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibroIdLbl;
    private javax.swing.JTextField LibroIdTxt;
    private javax.swing.JLabel authorLbl;
    private javax.swing.JTextField authorTxt;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton button;
    private javax.swing.JLabel catLbl;
    private javax.swing.JTextField catTxt;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descTxt;
    private javax.swing.JLabel dispLbl;
    private javax.swing.JTextField dispTxt;
    private javax.swing.JLabel edLbl;
    private javax.swing.JTextField edTxt;
    private javax.swing.JLabel ejemLbl;
    private javax.swing.JTextField ejemTxt;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel langLbl;
    private javax.swing.JTextField langTxt;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel pagsLbl;
    private javax.swing.JTextField pagsTxt;
    private javax.swing.JLabel stockLbl;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
